# Generated by Django 4.1.4 on 2022-12-11 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('pairingDate', models.DateTimeField(null=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isOwner', models.BooleanField(default=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretSanta.event')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('url', models.URLField()),
                ('eventUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretSanta.eventuser')),
            ],
        ),
        migrations.CreateModel(
            name='SantaPairing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('santaEventUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_santa', to='secretSanta.eventuser')),
                ('targetEventUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_target', to='secretSanta.eventuser')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusionPairing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventUser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_user1', to='secretSanta.eventuser')),
                ('eventUser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_user2', to='secretSanta.eventuser')),
            ],
        ),
    ]
